x-rnode: &default-rnode
  image: f1r3flyindustries/f1r3fly-rust-node:latest
  user: root
  networks:
    - f1r3fly
  environment:
    - OPENAI_ENABLED=${OPENAI_ENABLED}
    - OPENAI_SCALA_CLIENT_API_KEY=${OPENAI_SCALA_CLIENT_API_KEY}

services:
  boot:
    <<: *default-rnode
    container_name: ${BOOTSTRAP_HOST}
    restart: always
    healthcheck:
      disable: true
    command:
      [
        "run",
        "--host=${BOOTSTRAP_HOST}",
        "--bootstrap=rnode://${BOOTSTRAP_NODE_ID}@${BOOTSTRAP_HOST}?protocol=40400&discovery=40404",
        "--allow-private-addresses",
        "--validator-private-key=${BOOTSTRAP_PRIVATE_KEY}"
      ]
    ports:
      - "40400:40400"
      - "40401:40401"
      - "40402:40402"
      - "40403:40403"
      - "40404:40404"
      - "40405:40405"
    volumes:
      - ./data/${BOOTSTRAP_HOST}:/var/lib/rnode
      - ./genesis:/var/lib/rnode/genesis:ro

  validator1:
    <<: *default-rnode
    container_name: ${VALIDATOR1_HOST}
    restart: always
    healthcheck:
      disable: true
    command:
      [
        "run",
        "--host=${VALIDATOR1_HOST}",
        "--allow-private-addresses",
        "--bootstrap=rnode://${BOOTSTRAP_NODE_ID}@${BOOTSTRAP_HOST}?protocol=40400&discovery=40404",
        "--validator-public-key=${VALIDATOR1_PUBLIC_KEY}",
        "--validator-private-key=${VALIDATOR1_PRIVATE_KEY}",
        "--genesis-validator"
      ]
    ports:
      - "40410:40400"
      - "40411:40401"
      - "40412:40402"
      - "40413:40403"
      - "40414:40404"
      - "40415:40405"
    volumes:
      - ./data/${VALIDATOR1_HOST}:/var/lib/rnode
      - ./genesis:/var/lib/rnode/genesis:ro

  validator2:
    <<: *default-rnode
    container_name: ${VALIDATOR2_HOST}
    restart: always
    healthcheck:
      disable: true
    command:
      [
        "run",
        "--host=${VALIDATOR2_HOST}",
        "--allow-private-addresses",
        "--bootstrap=rnode://${BOOTSTRAP_NODE_ID}@${BOOTSTRAP_HOST}?protocol=40400&discovery=40404",
        "--validator-public-key=${VALIDATOR2_PUBLIC_KEY}",
        "--validator-private-key=${VALIDATOR2_PRIVATE_KEY}",
        "--genesis-validator"
      ]
    ports:
      - "40420:40400"
      - "40421:40401"
      - "40422:40402"
      - "40423:40403"
      - "40424:40404"
      - "40425:40405"
    volumes:
      - ./data/${VALIDATOR2_HOST}:/var/lib/rnode
      - ./genesis:/var/lib/rnode/genesis:ro

  validator3:
    <<: *default-rnode
    container_name: ${VALIDATOR3_HOST}
    restart: always
    healthcheck:
      disable: true
    command:
      [
        "run",
        "--host=${VALIDATOR3_HOST}",
        "--allow-private-addresses",
        "--bootstrap=rnode://${BOOTSTRAP_NODE_ID}@${BOOTSTRAP_HOST}?protocol=40400&discovery=40404",
        "--validator-public-key=${VALIDATOR3_PUBLIC_KEY}",
        "--validator-private-key=${VALIDATOR3_PRIVATE_KEY}",
        "--genesis-validator"
      ]
    ports:
      - "40430:40400"
      - "40431:40401"
      - "40432:40402"
      - "40433:40403"
      - "40434:40404"
      - "40435:40405"
    volumes:
      - ./data/${VALIDATOR3_HOST}:/var/lib/rnode
      - ./genesis:/var/lib/rnode/genesis:ro

networks:
  f1r3fly:
    driver: bridge