x-rnode: &default-rnode
  image: f1r3flyindustries/f1r3fly-scala-node
  pull_policy: always
  user: root
  networks:
    - f1r3fly
  environment:
    - OPENAI_ENABLED=${OPENAI_ENABLED}
    - OPENAI_SCALA_CLIENT_API_KEY=${OPENAI_SCALA_CLIENT_API_KEY}

services:
  boot:
    <<: *default-rnode
    container_name: $BOOTSTRAP_HOST
    restart: always
    command:
      [
        "-Dlogback.configurationFile=/var/lib/rnode/logback.xml",
        "run",
        "--host=$BOOTSTRAP_HOST",
        "--bootstrap=rnode://$BOOTSTRAP_NODE_ID@$BOOTSTRAP_HOST?protocol=40400&discovery=40404", # node will know it's bootstrap node
        "--allow-private-addresses",
        "--validator-private-key=$BOOTSTRAP_PRIVATE_KEY"
      ]
    ports:
      - "40400:40400"
      - "40401:40401"
      - "40402:40402"
      - "40403:40403"
      - "40404:40404"
      - "40405:40405"
    volumes:
      # Bootstrap-specific configuration (ceremony master)
      - ./conf/bootstrap-ceremony.conf:/var/lib/rnode/rnode.conf
      - ./genesis/wallets.txt:/var/lib/rnode/genesis/wallets.txt
      - ./genesis/bonds.txt:/var/lib/rnode/genesis/bonds.txt
      - ./conf/logback.xml:/var/lib/rnode/logback.xml
      # Node-specific volumes
      - ./data/$BOOTSTRAP_HOST:/var/lib/rnode/
      - ./certs/bootstrap/node.certificate.pem:/var/lib/rnode/node.certificate.pem:ro
      - ./certs/bootstrap/node.key.pem:/var/lib/rnode/node.key.pem:ro

  validator1:
    <<: *default-rnode
    container_name: $VALIDATOR1_HOST
    restart: always
    command:
      [
        "-Dlogback.configurationFile=/var/lib/rnode/logback.xml",
        "run",
        "--host=$VALIDATOR1_HOST",
        "--allow-private-addresses",
        "--bootstrap=rnode://$BOOTSTRAP_NODE_ID@$BOOTSTRAP_HOST?protocol=40400&discovery=40404",
        "--validator-public-key=$VALIDATOR1_PUBLIC_KEY",
        "--validator-private-key=$VALIDATOR1_PRIVATE_KEY",
        "--genesis-validator"
      ]
    ports:
      - "40410:40400"
      - "40411:40401"
      - "40412:40402"
      - "40413:40403"
      - "40414:40404"
      - "40415:40405"
    volumes:
      - ./conf/shared-rnode.conf:/var/lib/rnode/rnode.conf
      - ./genesis/wallets.txt:/var/lib/rnode/genesis/wallets.txt
      - ./genesis/bonds.txt:/var/lib/rnode/genesis/bonds.txt
      - ./conf/logback.xml:/var/lib/rnode/logback.xml
      - ./data/$VALIDATOR1_HOST:/var/lib/rnode/
      - ./certs/validator1/node.certificate.pem:/var/lib/rnode/node.certificate.pem:ro
      - ./certs/validator1/node.key.pem:/var/lib/rnode/node.key.pem:ro

  validator2:
    <<: *default-rnode
    container_name: $VALIDATOR2_HOST
    restart: always
    command:
      [
        "-Dlogback.configurationFile=/var/lib/rnode/logback.xml",
        "run",
        "--host=$VALIDATOR2_HOST",
        "--allow-private-addresses",
        "--bootstrap=rnode://$BOOTSTRAP_NODE_ID@$BOOTSTRAP_HOST?protocol=40400&discovery=40404",
        "--validator-public-key=$VALIDATOR2_PUBLIC_KEY",
        "--validator-private-key=$VALIDATOR2_PRIVATE_KEY",
        "--genesis-validator"
      ]
    ports:
      - "40420:40400"
      - "40421:40401"
      - "40422:40402"
      - "40423:40403"
      - "40424:40404"
      - "40425:40405"
    volumes:
      - ./conf/shared-rnode.conf:/var/lib/rnode/rnode.conf
      - ./genesis/wallets.txt:/var/lib/rnode/genesis/wallets.txt
      - ./genesis/bonds.txt:/var/lib/rnode/genesis/bonds.txt
      - ./conf/logback.xml:/var/lib/rnode/logback.xml
      - ./data/$VALIDATOR2_HOST:/var/lib/rnode/
      - ./certs/validator2/node.certificate.pem:/var/lib/rnode/node.certificate.pem:ro
      - ./certs/validator2/node.key.pem:/var/lib/rnode/node.key.pem:ro

  validator3:
    <<: *default-rnode
    container_name: $VALIDATOR3_HOST
    restart: always
    command:
      [
        "-Dlogback.configurationFile=/var/lib/rnode/logback.xml",
        "run",
        "--host=$VALIDATOR3_HOST",
        "--allow-private-addresses",
        "--bootstrap=rnode://$BOOTSTRAP_NODE_ID@$BOOTSTRAP_HOST?protocol=40400&discovery=40404",
        "--validator-public-key=$VALIDATOR3_PUBLIC_KEY",
        "--validator-private-key=$VALIDATOR3_PRIVATE_KEY",
        "--genesis-validator"
      ]
    ports:
      - "40430:40400"
      - "40431:40401"
      - "40432:40402"
      - "40433:40403"
      - "40434:40404"
      - "40435:40405"
    volumes:
      - ./conf/shared-rnode.conf:/var/lib/rnode/rnode.conf
      - ./genesis/wallets.txt:/var/lib/rnode/genesis/wallets.txt
      - ./genesis/bonds.txt:/var/lib/rnode/genesis/bonds.txt
      - ./conf/logback.xml:/var/lib/rnode/logback.xml
      - ./data/$VALIDATOR3_HOST:/var/lib/rnode/
      - ./certs/validator3/node.certificate.pem:/var/lib/rnode/node.certificate.pem:ro
      - ./certs/validator3/node.key.pem:/var/lib/rnode/node.key.pem:ro

  readonly:
    image: f1r3flyindustries/f1r3fly-scala-node
    pull_policy: always
    user: root
    networks:
      - f1r3fly
    container_name: $READONLY_HOST
    restart: always
    ports:
      - "40451:40401"
      - "40452:40402"
      - "40453:40403"
    command:
    - run
    - --host=$READONLY_HOST
    - --bootstrap=rnode://1e780e5dfbe0a3d9470a2b414f502d59402e09c2@$BOOTSTRAP_HOST?protocol=40400&discovery=40404
    - --no-upnp
    - --allow-private-addresses
    - -Dlogback.configurationFile=/var/lib/rnode/logback.xml

    volumes:
      - ./conf/logback.xml:/var/lib/rnode/logback.xml

networks:
  f1r3fly:
    driver: bridge 
